cd /home
java -Dtransports.netty.conf=msf4j-http-config.yaml -DOCR_SERVICE_HOST_NAME=$OCR_SERVICE_HOST_NAME -DOCR_SERVICE_PORT_NUMBER=$OCR_SERVICE_PORT_NUMBER -DTRANSLATION_SERVICE_HOST_NAME=$TRANSLATION_SERVICE_HOST_NAME -DTRANSLATION_SERVICE_PORT_NUMBER=$TRANSLATION_SERVICE_PORT_NUMBER -jar Cloudlet-0.0.1-SNAPSHOT.jar
